/** 55 interactive titles — full metadata for SaeroSero catalog */

export const CATALOG_TITLES = [
  { id: 'starlight-station', status: 'playable', genre: 'sf', age: '12', featured: true, hue: 198, episodes: 1,
    titles: { ko: '별빛 정거장', en: 'Starlight Station', ja: '星灯りの駅', 'zh-Hans': '星光车站', es: 'Estación Starlight' },
    logline: { ko: '궤도 정거장의 신호. 당신의 선택이 밤을 바갈다.', en: 'A signal on the orbital station. Your choices reshape the night.' },
    tags: ['sf', 'space', 'interactive'], characters: ['아리아', 'Aria'], posterScene: 'orbital station corridor, sci-fi anime' },
  { id: 'moonlit-harbor', status: 'development', genre: 'romance', age: '12', featured: true, hue: 215, episodes: 0,
    titles: { ko: '달빛 항구', en: 'Moonlit Harbor', ja: '月明かりの港', 'zh-Hans': '月光港湾', es: 'Puerto Lunar' },
    logline: { ko: '파도가 사랑을 배달하는 밤의 항구.', en: 'A harbor where tides deliver lost love letters.' },
    tags: ['romance', 'sea'], characters: ['하린', 'Harin'], posterScene: 'moonlit pier, romantic anime harbor' },
  { id: 'quantum-letters', status: 'development', genre: 'mystery', age: '15', featured: true, hue: 262, episodes: 0,
    titles: { ko: '양자 우편', en: 'Quantum Letters', ja: '量子の手紙', 'zh-Hans': '量子书信', es: 'Cartas Cuánticas' },
    logline: { ko: '도착하기 전에 읽히는 편지들.', en: 'Letters that are read before they arrive.' },
    tags: ['mystery', 'sci-fi'], characters: ['이준', 'Jun'], posterScene: 'glowing envelopes in quantum void' },
  { id: 'neon-samaritan', status: 'coming_soon', genre: 'sf', age: '15', featured: true, hue: 185,
    titles: { ko: '네온 사마리아', en: 'Neon Samaritan', ja: 'ネオン・サマリタン', 'zh-Hans': '霓虹善人', es: 'El Samaritano Neón' },
    logline: { ko: '사이버 슬럼에서 정의를 배달하는 자.', en: 'A courier of justice in the neon slums.' },
    posterScene: 'cyberpunk alley rain neon signs' },
  { id: 'glass-garden', status: 'coming_soon', genre: 'fantasy', age: 'all', featured: true, hue: 145,
    titles: { ko: '유리 정원', en: 'Glass Garden', ja: 'ガラスの庭', 'zh-Hans': '玻璃花园', es: 'Jardín de Cristal' },
    logline: { ko: '시간이 꽃처럼 자라는 온실.', en: 'A greenhouse where time blooms like flowers.' },
    posterScene: 'crystal greenhouse fantasy flowers' },
  { id: 'last-orchestra', status: 'coming_soon', genre: 'drama', age: '12', featured: true, hue: 32,
    titles: { ko: '마지막 오케스트라', en: 'The Last Orchestra', ja: '最後のオーケストラ', 'zh-Hans': '最后的乐团', es: 'La Última Orquesta' },
    logline: { ko: '세상이 조용해지기 전 마지막 연주.', en: 'One final performance before the world goes silent.' },
    posterScene: 'empty concert hall golden light' },
  { id: 'iron-bloom', status: 'coming_soon', genre: 'action', age: '15', hue: 8,
    titles: { ko: '강철 꽃', en: 'Iron Bloom', ja: '鋼鉄の花', 'zh-Hans': '钢铁之花', es: 'Flor de Hierro' },
    logline: { ko: '폐허에서 피어난 기계 검사.', en: 'A blade-forged knight risen from ruins.' },
    posterScene: 'mecha warrior ruins sunset' },
  { id: 'silent-witness', status: 'coming_soon', genre: 'thriller', age: '19', hue: 228,
    titles: { ko: '침묵의 목격자', en: 'Silent Witness', ja: '沈黙の目撃者', 'zh-Hans': '沉默的目击者', es: 'Testigo Silencioso' },
    logline: { ko: '기억을 훔친 도시의 감시 카메라.', en: 'Surveillance feeds that steal memories.' },
    posterScene: 'noir detective rain city' },
  { id: 'candy-orbit', status: 'coming_soon', genre: 'romance', age: 'all', hue: 310,
    titles: { ko: '캔디 궤도', en: 'Candy Orbit', ja: 'キャンディ軌道', 'zh-Hans': '糖果轨道', es: 'Órbita de Caramelo' },
    logline: { ko: '행성 사이를 오가는 달콤한 우주 편지.', en: 'Sweet letters drifting between tiny planets.' },
    posterScene: 'cute planets pastel space romance' },
  { id: 'paper-comet', status: 'coming_soon', genre: 'fantasy', age: '12', hue: 52,
    titles: { ko: '종이 혜성', en: 'Paper Comet', ja: '紙の彗星', 'zh-Hans': '纸彗星', es: 'Cometa de Papel' },
    logline: { ko: '소원을 적으면 하늘을 가르는 편지.', en: 'Write a wish; the letter tears the sky.' },
    posterScene: 'origami comet starry sky' },
  { id: 'deep-signal', status: 'coming_soon', genre: 'sf', age: '15', hue: 205,
    titles: { ko: '심해 신호', en: 'Deep Signal', ja: '深海信号', 'zh-Hans': '深海信号', es: 'Señal Abisal' },
    logline: { ko: '해저 4km에서 온 인류 이전의 코드.', en: 'Pre-human code pulsing from the abyss.' },
    posterScene: 'submarine abyss bioluminescence' },
  { id: 'velvet-rebellion', status: 'coming_soon', genre: 'drama', age: '19', hue: 340,
    titles: { ko: '벨벳 반란', en: 'Velvet Rebellion', ja: 'ベルベットの反乱', 'zh-Hans': '天鹅绒叛乱', es: 'Rebelión de Terciopelo' },
    logline: { ko: '무대 뒤에서 일어난 궁정의 음모.', en: 'Court intrigue behind the velvet curtain.' },
    posterScene: 'theater stage red curtain drama' },
  { id: 'clockwork-rain', status: 'coming_soon', genre: 'fantasy', age: '12', hue: 175,
    titles: { ko: '시계태엽 비', en: 'Clockwork Rain', ja: '時計仕掛けの雨', 'zh-Hans': '发条之雨', es: 'Lluvia de Relojes' },
    logline: { ko: '비 한 방울마다 하루가 되감긴다.', en: 'Each raindrop rewinds one day.' },
    posterScene: 'steampunk city raining gears' },
  { id: 'hollow-echo', status: 'coming_soon', genre: 'mystery', age: '15', hue: 248,
    titles: { ko: '공허의 메아리', en: 'Hollow Echo', ja: '虚ろのこだま', 'zh-Hans': '空洞回响', es: 'Eco Hueco' },
    logline: { ko: '삭제된 목소리가 터널에 남긴 흔적.', en: 'Deleted voices still resonate in the tunnel.' },
    posterScene: 'abandoned subway mysterious light' },
  { id: 'solar-ash', status: 'coming_soon', genre: 'action', age: '15', hue: 18,
    titles: { ko: '태양 잿더미', en: 'Solar Ash', ja: '太陽の灰', 'zh-Hans': '太阳灰烬', es: 'Ceniza Solar' },
    logline: { ko: '타버린 행성을 가로지르는 도주.', en: 'Escape across a scorched frontier world.' },
    posterScene: 'desert warrior solar flare' },
  { id: 'mirror-lake', status: 'coming_soon', genre: 'romance', age: '12', hue: 192,
    titles: { ko: '거울 호수', en: 'Mirror Lake', ja: '鏡の湖', 'zh-Hans': '镜湖', es: 'Lago Espejo' },
    logline: { ko: '반영된 자신과 다시 만나는 여름.', en: 'A summer reunion with your reflected self.' },
    posterScene: 'lake reflection two figures anime' },
  { id: 'fractal-dream', status: 'coming_soon', genre: 'sf', age: '12', hue: 280,
    titles: { ko: '프랙탈 드림', en: 'Fractal Dream', ja: 'フラクタル・ドリーム', 'zh-Hans': '分形之梦', es: 'Sueño Fractal' },
    logline: { ko: '무한히 반복되는 꿈의 시뮬레이션.', en: 'A simulation of endlessly repeating dreams.' },
    posterScene: 'fractal tunnel digital dream' },
  { id: 'ember-chronicle', status: 'coming_soon', genre: 'fantasy', age: '15', hue: 24,
    titles: { ko: '잔불 연대기', en: 'Ember Chronicle', ja: '残火年代記', 'zh-Hans': '余烬纪', es: 'Crónica de Brasas' },
    logline: { ko: '멸망한 왕국의 마지막 화염 마법사.', en: 'The last flame mage of a fallen kingdom.' },
    posterScene: 'fire mage castle ruins fantasy' },
  { id: 'zero-gravity-waltz', status: 'coming_soon', genre: 'romance', age: 'all', hue: 300,
    titles: { ko: '무중력 왈츠', en: 'Zero Gravity Waltz', ja: '無重力ワルツ', 'zh-Hans': '零重力华尔兹', es: 'Vals en Gravedad Cero' },
    logline: { ko: '떠다니는 연주회에서의 첫 춤.', en: 'A first dance at a floating concert.' },
    posterScene: 'couple dancing zero gravity ballroom' },
  { id: 'crimson-archive', status: 'coming_soon', genre: 'thriller', age: '19', hue: 355,
    titles: { ko: '진홍 기록원', en: 'Crimson Archive', ja: '深紅の記録院', 'zh-Hans': '深红档案库', es: 'Archivo Carmesí' },
    logline: { ko: '삭제 금지된 사건만 모아둔 도서관.', en: 'A library of forbidden case files.' },
    posterScene: 'dark library red candles thriller' },
  { id: 'sky-pilgrim', status: 'coming_soon', genre: 'action', age: '12', hue: 42,
    titles: { ko: '하늘 순례자', en: 'Sky Pilgrim', ja: '空の巡礼者', 'zh-Hans': '天空朝圣者', es: 'Peregrino del Cielo' },
    logline: { ko: '떠다니는 사원을 향한 격투 순례.', en: 'A martial pilgrimage to a floating temple.' },
    posterScene: 'monk leaping floating temples' },
  { id: 'petal-strike', status: 'coming_soon', genre: 'action', age: '15', hue: 330,
    titles: { ko: '꽃잎 타격', en: 'Petal Strike', ja: '花弁の一撃', 'zh-Hans': '花瓣一击', es: 'Golpe de Pétalos' },
    logline: { ko: '검객이 꽃으로 베는 비밀 결투.', en: 'Secret duels where blades are made of petals.' },
    posterScene: 'swordsman cherry blossoms action' },
  { id: 'winter-circuit', status: 'coming_soon', genre: 'sf', age: '12', hue: 210,
    titles: { ko: '겨울 회로', en: 'Winter Circuit', ja: '冬の回路', 'zh-Hans': '冬日回路', es: 'Circuito Invernal' },
    logline: { ko: '영구 동토 아래 숨은 도시의 AI.', en: 'An AI awakening beneath the permafrost city.' },
    posterScene: 'frozen city circuits blue ice' },
  { id: 'honey-theorem', status: 'coming_soon', genre: 'drama', age: 'all', hue: 38,
    titles: { ko: '꿀 정리', en: 'Honey Theorem', ja: '蜂蜜定理', 'zh-Hans': '蜂蜜定理', es: 'Teorema de Miel' },
    logline: { ko: '수학과 요리로 가족을 붙잡는 공식.', en: 'A formula to hold a family together with math and cooking.' },
    posterScene: 'warm kitchen sunlight family drama' },
  { id: 'lunar-cartographer', status: 'coming_soon', genre: 'mystery', age: '12', hue: 235,
    titles: { ko: '달 지도 제작자', en: 'Lunar Cartographer', ja: '月の地図師', 'zh-Hans': '月面制图师', es: 'Cartógrafo Lunar' },
    logline: { ko: '달에만 존재하는 거리를 그리는 소녀.', en: 'A girl mapping streets that exist only on the moon.' },
    posterScene: 'girl mapping moon surface mystery' },
  { id: 'azure-veil', status: 'coming_soon', genre: 'romance', age: '15', hue: 200,
    titles: { ko: '청색 베일', en: 'Azure Veil', ja: '蒼いベール', 'zh-Hans': '青纱', es: 'Velo Azur' },
    logline: { ko: '신부의 면사포 너머의 다른 정체.', en: 'Another identity behind the azure wedding veil.' },
    posterScene: 'bride blue veil wind romance' },
  { id: 'static-paradise', status: 'coming_soon', genre: 'thriller', age: '19', hue: 160,
    titles: { ko: '잡음 낙원', en: 'Static Paradise', ja: '雑音の楽園', 'zh-Hans': '噪点乐园', es: 'Paraíso Estático' },
    logline: { ko: '완벽한 마을의 TV 잡음 속 진실.', en: 'Truth hidden in the static of a perfect town.' },
    posterScene: 'suburban horror TV static' },
  { id: 'dragon-sidestreet', status: 'coming_soon', genre: 'fantasy', age: '12', hue: 118,
    titles: { ko: '용의 골목', en: 'Dragon Sidestreet', ja: '龍の路地', 'zh-Hans': '龙之小巷', es: 'Callejón del Dragón' },
    logline: { ko: '대도시 뒤편에 숨은 미니어처 용.', en: 'A miniature dragon hidden in the city back alleys.' },
    posterScene: 'small dragon neon alley fantasy' },
  { id: 'binary-sonata', status: 'coming_soon', genre: 'sf', age: '15', hue: 188,
    titles: { ko: '바이너리 소나타', en: 'Binary Sonata', ja: 'バイナリソナタ', 'zh-Hans': '二进制奏鸣曲', es: 'Sonata Binaria' },
    logline: { ko: '두 AI가 함께 쓴 교향곡의 버그.', en: 'A symphony co-written by two AIs—now glitching.' },
    posterScene: 'piano hologram code symphony' },
  { id: 'frost-letter', status: 'coming_soon', genre: 'romance', age: '12', hue: 195,
    titles: { ko: '서리 편지', en: 'Frost Letter', ja: '霜の手紙', 'zh-Hans': '霜信', es: 'Carta de Escarcha' },
    logline: { ko: '겨울마다 창문에 나타나는 이름.', en: 'A name that appears on the window each winter.' },
    posterScene: 'frost window letter romance' },
  { id: 'obsidian-circus', status: 'coming_soon', genre: 'fantasy', age: '15', hue: 268,
    titles: { ko: '흑요석 서커스', en: 'Obsidian Circus', ja: '黒曜石サーカス', 'zh-Hans': '黑曜马戏团', es: 'Circo de Obsidiana' },
    logline: { ko: '자정에만 열리는 칠흑 텐트.', en: 'A pitch-black tent that opens only at midnight.' },
    posterScene: 'dark circus tent purple lights' },
  { id: 'parallel-bookshop', status: 'coming_soon', genre: 'mystery', age: 'all', hue: 88,
    titles: { ko: '평행 서점', en: 'Parallel Bookshop', ja: '平行書店', 'zh-Hans': '平行书店', es: 'Librería Paralela' },
    logline: { ko: '다른 세계의 자신이 쓴 책만 판다.', en: 'A shop that sells books written by your other selves.' },
    posterScene: 'cozy bookshop portals mystery' },
  { id: 'thunder-bloom', status: 'coming_soon', genre: 'action', age: '15', hue: 55,
    titles: { ko: '뇌전 개화', en: 'Thunder Bloom', ja: '雷花', 'zh-Hans': '雷花', es: 'Flor del Trueno' },
    logline: { ko: '번개 속에서만 피는 꽃을 지키는 자.', en: 'Guardians of flowers that bloom only in lightning.' },
    posterScene: 'lightning field warrior flowers' },
  { id: 'sandglass-children', status: 'coming_soon', genre: 'drama', age: '12', hue: 28,
    titles: { ko: '모래시계 아이들', en: 'Sandglass Children', ja: '砂時計の子供たち', 'zh-Hans': '沙漏之子', es: 'Niños del Reloj de Arena' },
    logline: { ko: '시간이 거꾸로 흐르는 마을의 성장.', en: 'Growing up in a town where time runs backward.' },
    posterScene: 'children sandglass village sunset' },
  { id: 'violet-border', status: 'coming_soon', genre: 'thriller', age: '19', hue: 275,
    titles: { ko: '보라색 국경', en: 'Violet Border', ja: '紫の国境', 'zh-Hans': '紫色边境', es: 'Frontera Violeta' },
    logline: { ko: '국경 검문소에서 사라진 여권의 주인.', en: 'The owner of a passport that vanished at customs.' },
    posterScene: 'border checkpoint fog thriller' },
  { id: 'starfruit-cafe', status: 'coming_soon', genre: 'romance', age: 'all', hue: 315,
    titles: { ko: '스타프루트 카페', en: 'Starfruit Café', ja: 'スターフルーツカフェ', 'zh-Hans': '杨桃咖啡馆', es: 'Café Carambola' },
    logline: { ko: '별 모양 과일이 인연을 맺어주는 곳.', en: 'Where star-shaped fruit pairs destined lovers.' },
    posterScene: 'cozy cafe starfruit romance' },
  { id: 'gravity-waltz', status: 'coming_soon', genre: 'sf', age: '12', hue: 182,
    titles: { ko: '중력 왈츠', en: 'Gravity Waltz', ja: '重力ワルツ', 'zh-Hans': '重力华尔兹', es: 'Vals Gravitacional' },
    logline: { ko: '중력이 바뀌는 행성의 첫 축제.', en: 'The first festival on a planet of shifting gravity.' },
    posterScene: 'floating festival planet sci-fi' },
  { id: 'ink-republic', status: 'coming_soon', genre: 'fantasy', age: '15', hue: 220,
    titles: { ko: '잉크 공화국', en: 'Ink Republic', ja: 'インク共和国', 'zh-Hans': '墨水共和国', es: 'República de Tinta' },
    logline: { ko: '말이 현실이 되는 만화 왕국.', en: 'A comic kingdom where spoken words become real.' },
    posterScene: 'ink ocean floating islands fantasy' },
  { id: 'afterglow-taxi', status: 'coming_soon', genre: 'drama', age: '15', hue: 14,
    titles: { ko: '애프터글로 택시', en: 'Afterglow Taxi', ja: 'アフターグロウ・タクシー', 'zh-Hans': '余晖出租车', es: 'Taxi del Ocaso' },
    logline: { ko: '저녁노을만 태우는 기사의 마지막 승객.', en: 'A driver who only picks up passengers at sunset.' },
    posterScene: 'taxi sunset city drama' },
  { id: 'coral-code', status: 'coming_soon', genre: 'sf', age: '12', hue: 168,
    titles: { ko: '산호 코드', en: 'Coral Code', ja: '珊瑚コード', 'zh-Hans': '珊瑚代码', es: 'Código Coral' },
    logline: { ko: '살아 있는 산호가 기록한 바다의 역사.', en: 'Living coral archiving the ocean\'s history.' },
    posterScene: 'underwater coral reef sci-fi' },
  { id: 'phantom-bakery', status: 'coming_soon', genre: 'mystery', age: 'all', hue: 45,
    titles: { ko: '유령 제과점', en: 'Phantom Bakery', ja: '幻影のパン屋', 'zh-Hans': '幽灵面包店', es: 'Panadería Fantasma' },
    logline: { ko: '새벽 3시에만 문을 여는 빵집.', en: 'A bakery that opens only at 3 a.m.' },
    posterScene: 'bakery night warm light mystery' },
  { id: 'silver-tide', status: 'coming_soon', genre: 'romance', age: '12', hue: 208,
    titles: { ko: '은빛 조수', en: 'Silver Tide', ja: '銀の潮', 'zh-Hans': '银潮', es: 'Marea Plateada' },
    logline: { ko: '밀물마다 다시 찾아오는 그 사람.', en: 'Someone who returns with every high tide.' },
    posterScene: 'silver beach tide romance' },
  { id: 'bone-garden', status: 'coming_soon', genre: 'thriller', age: '19', hue: 95,
    titles: { ko: '뼈 정원', en: 'Bone Garden', ja: '骨の庭', 'zh-Hans': '骨园', es: 'Jardín de Huesos' },
    logline: { ko: '화분 아래 묻힌 도시의 기록.', en: 'Records of a city buried beneath the planters.' },
    posterScene: 'gothic garden bones thriller' },
  { id: 'meteor-alley', status: 'coming_soon', genre: 'action', age: '12', hue: 12,
    titles: { ko: '유성 골목', en: 'Meteor Alley', ja: '流星路地', 'zh-Hans': '流星巷', es: 'Callejón Meteoro' },
    logline: { ko: '떨어지는 별을 쫓는 소년 갱단.', en: 'A gang of kids chasing falling stars.' },
    posterScene: 'kids rooftop meteor shower action' },
  { id: 'cloud-architect', status: 'coming_soon', genre: 'fantasy', age: 'all', hue: 190,
    titles: { ko: '구름 건축가', en: 'Cloud Architect', ja: '雲の建築家', 'zh-Hans': '云朵建筑师', es: 'Arquitecto de Nubes' },
    logline: { ko: '하늘에 집을 짓는 소녀의 설계도.', en: 'Blueprints for houses built in the sky.' },
    posterScene: 'girl building cloud castles' },
  { id: 'echo-chamber', status: 'coming_soon', genre: 'mystery', age: '15', hue: 252,
    titles: { ko: '메아리 방', en: 'Echo Chamber', ja: '反響室', 'zh-Hans': '回音室', es: 'Cámara de Eco' },
    logline: { ko: '말이 물리적으로 되돌아오는 방.', en: 'A room where spoken words physically return.' },
    posterScene: 'sound waves room mystery' },
  { id: 'prism-runner', status: 'coming_soon', genre: 'action', age: '15', hue: 290,
    titles: { ko: '프리즘 러너', en: 'Prism Runner', ja: 'プリズムランナー', 'zh-Hans': '棱镜跑者', es: 'Corredor Prisma' },
    logline: { ko: '빛을 밟고 달리는 도시의 배달부.', en: 'A courier who runs on beams of light.' },
    posterScene: 'parkour light beams city' },
  { id: 'cedar-ghost', status: 'coming_soon', genre: 'drama', age: '15', hue: 125,
    titles: { ko: '삼나무 유령', en: 'Cedar Ghost', ja: '杉の幽霊', 'zh-Hans': '雪松幽灵', es: 'Fantasma del Cedro' },
    logline: { ko: '숲에서 돌아온 형의 목소리.', en: 'A brother\'s voice returning from the forest.' },
    posterScene: 'cedar forest fog drama' },
  { id: 'opal-scar', status: 'coming_soon', genre: 'thriller', age: '19', hue: 185,
    titles: { ko: '오팔의 흉터', en: 'Opal Scar', ja: 'オパールの傷', 'zh-Hans': '欧泊伤疤', es: 'Cicatriz de Ópalo' },
    logline: { ko: '보석 속에 갇힌 범인의 얼굴.', en: 'A criminal\'s face trapped inside a gemstone.' },
    posterScene: 'gemstone macro face thriller' },
  { id: 'sugar-orbit', status: 'coming_soon', genre: 'romance', age: 'all', hue: 305,
    titles: { ko: '슈가 궤도', en: 'Sugar Orbit', ja: 'シューガー軌道', 'zh-Hans': '糖轨', es: 'Órbita Azucarada' },
    logline: { ko: '사탕 행성을 도는 두 우주인의 데이트.', en: 'A date orbiting a planet made of candy.' },
    posterScene: 'candy planet couple space romance' },
  { id: 'titan-letters', status: 'coming_soon', genre: 'sf', age: '15', hue: 178,
    titles: { ko: '타이탄 서신', en: 'Titan Letters', ja: 'タイタンの手紙', 'zh-Hans': '泰坦来信', es: 'Cartas de Titán' },
    logline: { ko: '흙의 위성에서 온 80년 늦은 편지.', en: 'Letters from Titan, delivered eighty years late.' },
    posterScene: 'titan moon methane lakes sci-fi' },
  { id: 'moss-cathedral', status: 'coming_soon', genre: 'fantasy', age: '12', hue: 135,
    titles: { ko: '이끼 대성당', en: 'Moss Cathedral', ja: '苔の大聖堂', 'zh-Hans': '苔藓大教堂', es: 'Catedral de Musgo' },
    logline: { ko: '숲이 예배당이 된 뒤의 기도.', en: 'Prayers after the forest became a cathedral.' },
    posterScene: 'moss cathedral forest fantasy' },
  { id: 'neon-rosary', status: 'coming_soon', genre: 'drama', age: '19', hue: 295,
    titles: { ko: '네온 묵주', en: 'Neon Rosary', ja: 'ネオンのロザリオ', 'zh-Hans': '霓虹玫瑰经', es: 'Rosario de Neón' },
    logline: { ko: '사이버 성당에서의 고백.', en: 'Confession in a cybernetic cathedral.' },
    posterScene: 'neon church cyber drama' },
  { id: 'ash-piano', status: 'coming_soon', genre: 'drama', age: '12', hue: 0,
    titles: { ko: '잿빛 피아노', en: 'Ash Piano', ja: '灰のピアノ', 'zh-Hans': '灰烬钢琴', es: 'Piano de Ceniza' },
    logline: { ko: '화재 이후 남은 건반의 기억.', en: 'Memories trapped in keys after the fire.' },
    posterScene: 'burnt piano embers drama' },
  { id: 'wolf-hour', status: 'coming_soon', genre: 'thriller', age: '19', hue: 215,
    titles: { ko: '늑대의 시간', en: 'Wolf Hour', ja: '狼の時間', 'zh-Hans': '狼之时', es: 'Hora del Lobo' },
    logline: { ko: '새벽 4시, 모든 거짓말이 통하는 시각.', en: 'At 4 a.m., every lie becomes believable.' },
    posterScene: 'wolf silhouette clock thriller' },
  { id: 'pixel-garden', status: 'coming_soon', genre: 'fantasy', age: 'all', hue: 110,
    titles: { ko: '픽셀 정원', en: 'Pixel Garden', ja: 'ピクセル庭園', 'zh-Hans': '像素花园', es: 'Jardín Pixel' },
    logline: { ko: '8비트 꽃이 자라는 현실의 틈.', en: 'A crack in reality where 8-bit flowers grow.' },
    posterScene: 'pixel flowers real world fantasy' },
  { id: 'aurora-debt', status: 'coming_soon', genre: 'mystery', age: '15', hue: 165,
    titles: { ko: '오로라 부채', en: 'Aurora Debt', ja: 'オーロラの負債', 'zh-Hans': '极光债务', es: 'Deuda de Aurora' },
    logline: { ko: '빛을 빌려주는 자의 계약서.', en: 'A contract with one who lends the northern lights.' },
    posterScene: 'aurora borealis contract mystery' },
  { id: 'cinder-knight', status: 'coming_soon', genre: 'action', age: '15', hue: 20,
    titles: { ko: '잔화 기사', en: 'Cinder Knight', ja: '残火の騎士', 'zh-Hans': '余烬骑士', es: 'Caballero de Brasas' },
    logline: { ko: '불꽃이 식기 전에 적을 베는 자.', en: 'Strike the foe before the embers die.' },
    posterScene: 'knight flame sword action' },
  { id: 'tideglass', status: 'coming_soon', genre: 'romance', age: '12', hue: 188,
    titles: { ko: '조수 유리', en: 'Tideglass', ja: '潮glass', 'zh-Hans': '潮汐玻璃', es: 'Vidrio de Marea' },
    logline: { ko: '밀물에만 보이는 유리섬의 연인.', en: 'Lovers on a glass isle visible only at high tide.' },
    posterScene: 'glass island ocean romance' },
  { id: 'rootbound', status: 'coming_soon', genre: 'fantasy', age: '15', hue: 100,
    titles: { ko: '뿌리 결속', en: 'Rootbound', ja: '根に縛られて', 'zh-Hans': '根缚', es: 'Atado a la Raíz' },
    logline: { ko: '나무와 감정이 연결된 마을.', en: 'A village where trees share human emotions.' },
    posterScene: 'tree roots village fantasy' },
  { id: 'satellite-rain', status: 'coming_soon', genre: 'sf', age: '12', hue: 202,
    titles: { ko: '위성 비', en: 'Satellite Rain', ja: '衛星の雨', 'zh-Hans': '卫星之雨', es: 'Lluvia de Satélites' },
    logline: { ko: '하늘에서 떨어지는 고장 난 인공위성.', en: 'Broken satellites raining from the sky.' },
    posterScene: 'satellites falling sky sci-fi' },
  { id: 'chalk-revolution', status: 'coming_soon', genre: 'drama', age: '15', hue: 48,
    titles: { ko: '분필 혁명', en: 'Chalk Revolution', ja: 'チョーク革命', 'zh-Hans': '粉笔革命', es: 'Revolución de Tiza' },
    logline: { ko: '칠판에 쓴 꿈이 거리를 점령할 때.', en: 'When dreams on the chalkboard occupy the streets.' },
    posterScene: 'classroom chalk protest drama' },
  { id: 'ivory-labyrinth', status: 'coming_soon', genre: 'mystery', age: '19', hue: 40,
    titles: { ko: '상아 미궁', en: 'Ivory Labyrinth', ja: '象牙の迷宮', 'zh-Hans': '象牙迷宫', es: 'Laberinto de Marfil' },
    logline: { ko: '피아노 건반처럼 배열된 살인 미로.', en: 'A murder maze laid like piano keys.' },
    posterScene: 'ivory maze mystery corridors' },
  { id: 'storm-telegram', status: 'coming_soon', genre: 'thriller', age: '15', hue: 230,
    titles: { ko: '폭풍 전보', en: 'Storm Telegram', ja: '嵐の電報', 'zh-Hans': '风暴电报', es: 'Telegrama de Tormenta' },
    logline: { ko: '번개마다 도착하는 살인 예고.', en: 'Murder warnings that arrive with each lightning bolt.' },
    posterScene: 'storm lighthouse telegram thriller' },
  { id: 'halo-market', status: 'coming_soon', genre: 'fantasy', age: 'all', hue: 55,
    titles: { ko: '후광 시장', en: 'Halo Market', ja: '後光の市場', 'zh-Hans': '光环集市', es: 'Mercado del Halo' },
    logline: { ko: '천사의 잃어버린 후광을 파는 골목.', en: 'An alley market selling lost angel halos.' },
    posterScene: 'fantasy market glowing halos' },
  { id: 'rust-symphony', status: 'coming_soon', genre: 'action', age: '15', hue: 16,
    titles: { ko: '녹슨 교향곡', en: 'Rust Symphony', ja: '錆の交響曲', 'zh-Hans': '铁锈交响曲', es: 'Sinfonía de Óxido' },
    logline: { ko: '폐공장의 기계들이 다시 울릴 때.', en: 'When the machines of a dead factory play again.' },
    posterScene: 'rust factory robots action' },
  { id: 'pearl-diver', status: 'coming_soon', genre: 'romance', age: '12', hue: 186,
    titles: { ko: '진주 잠수사', en: 'Pearl Diver', ja: '真珠の潜水夫', 'zh-Hans': '采珠人', es: 'Buzo de Perlas' },
    logline: { ko: '심해에서 찾은 것은 진주가 아니었다.', en: 'What she found in the deep was not a pearl.' },
    posterScene: 'pearl diver underwater romance' },
  { id: 'ghost-frequency', status: 'coming_soon', genre: 'sf', age: '15', hue: 240,
    titles: { ko: '유령 주파수', en: 'Ghost Frequency', ja: '幽霊周波数', 'zh-Hans': '幽灵频率', es: 'Frecuencia Fantasma' },
    logline: { ko: '죽은 방송국의 신호가 다시 잡히다.', en: 'A dead station\'s signal comes back on air.' },
    posterScene: 'radio tower ghost signal sci-fi' },
  { id: 'saffron-gate', status: 'coming_soon', genre: 'fantasy', age: '12', hue: 35,
    titles: { ko: '샤프란 문', en: 'Saffron Gate', ja: 'サフランの門', 'zh-Hans': '藏红花之门', es: 'Puerta de Azafrán' },
    logline: { ko: '향신료로 그려진 차원의 문.', en: 'A dimensional gate drawn with spices.' },
    posterScene: 'spice gate portal fantasy' },
  { id: 'midnight-express', status: 'coming_soon', genre: 'thriller', age: '19', hue: 250,
    titles: { ko: '미드나잇 익스프레스', en: 'Midnight Express', ja: 'ミッドナイト急行', 'zh-Hans': '午夜快车', es: 'Expreso de Medianoche' },
    logline: { ko: '종착역이 없는 자정 열차의 승객.', en: 'Passengers on a midnight train with no terminus.' },
    posterScene: 'midnight train thriller fog' },
  { id: 'canvas-revolt', status: 'coming_soon', genre: 'drama', age: '15', hue: 285,
    titles: { ko: '캔버스 반란', en: 'Canvas Revolt', ja: 'キャンバスの反乱', 'zh-Hans': '画布反叛', es: 'Revuelta del Lienzo' },
    logline: { ko: '그림 속 인물이罷工하는 날.', en: 'The day figures in paintings go on strike.' },
    posterScene: 'painted figures stepping out drama' },
  { id: 'zenith-blade', status: 'coming_soon', genre: 'action', age: '15', hue: 5,
    titles: { ko: '천정의 검', en: 'Zenith Blade', ja: '天頂の剣', 'zh-Hans': '天顶之剑', es: 'Espada del Cenit' },
    logline: { ko: '정오의 태양을 베는 검술.', en: 'A sword style that cuts the noon sun.' },
    posterScene: 'swordsman sun zenith action' },
  { id: 'lotus-circuit', status: 'coming_soon', genre: 'sf', age: '12', hue: 158,
    titles: { ko: '연꽃 회로', en: 'Lotus Circuit', ja: '蓮の回路', 'zh-Hans': '莲花回路', es: 'Circuito de Loto' },
    logline: { ko: '연못 아래 숨은 양자 서버.', en: 'A quantum server hidden beneath the lotus pond.' },
    posterScene: 'lotus pond cyber circuits' },
  { id: 'fable-warehouse', status: 'coming_soon', genre: 'mystery', age: 'all', hue: 72,
    titles: { ko: '우화 창고', en: 'Fable Warehouse', ja: '寓話の倉庫', 'zh-Hans': '寓言仓库', es: 'Almacén de Fábulas' },
    logline: { ko: '잊힌 동화가 박스에 포장되어 있다.', en: 'Forgotten fables packed in dusty boxes.' },
    posterScene: 'warehouse fairy tales boxes' },
  { id: 'ether-bride', status: 'coming_soon', genre: 'romance', age: '15', hue: 298,
    titles: { ko: '에테르 신부', en: 'Ether Bride', ja: 'エーテルの花嫁', 'zh-Hans': '以太新娘', es: 'Novia del Éter' },
    logline: { ko: '눈에 보이지 않는 약혼자의 초대장.', en: 'An invitation from an invisible fiancé.' },
    posterScene: 'ethereal bride veil romance' },
  { id: 'basalt-song', status: 'coming_soon', genre: 'drama', age: '12', hue: 25,
    titles: { ko: '현무암 노래', en: 'Basalt Song', ja: '玄武岩の歌', 'zh-Hans': '玄武岩之歌', es: 'Canción de Basalto' },
    logline: { ko: '화산 섬에서 이어지는 세대의 합창.', en: 'Generations singing on a volcanic isle.' },
    posterScene: 'volcanic island choir drama' },
  { id: 'cobalt-mirage', status: 'coming_soon', genre: 'thriller', age: '19', hue: 210,
    titles: { ko: '코발트 신기루', en: 'Cobalt Mirage', ja: 'コバルトの蜃気楼', 'zh-Hans': '钴蓝海市蜃楼', es: 'Espejismo de Cobalto' },
    logline: { ko: '사막에 비친 도시는 실종된 고향.', en: 'A city reflected in the desert is a vanished hometown.' },
    posterScene: 'desert mirage city thriller' },
  { id: 'dawn-protocol', status: 'coming_soon', genre: 'sf', age: '15', hue: 32,
    titles: { ko: '새벽 프로토콜', en: 'Dawn Protocol', ja: '夜明けプロトコル', 'zh-Hans': '黎明协议', es: 'Protocolo del Alba' },
    logline: { ko: '해가 뜨면 초기화되는 인공의식.', en: 'An artificial mind reset at every sunrise.' },
    posterScene: 'sunrise AI reset sci-fi' },
  { id: 'whisper-factory', status: 'coming_soon', genre: 'mystery', age: '15', hue: 265,
    titles: { ko: '속삭임 공장', en: 'Whisper Factory', ja: '囁きの工場', 'zh-Hans': '低语工厂', es: 'Fábrica de Susurros' },
    logline: { ko: '비밀을 대량 생산하는 산업 단지.', en: 'An industrial zone that mass-produces secrets.' },
    posterScene: 'factory whispers smoke mystery' },
  { id: 'jade-rebellion', status: 'coming_soon', genre: 'action', age: '15', hue: 140,
    titles: { ko: '비취 반란', en: 'Jade Rebellion', ja: '翡翠の反乱', 'zh-Hans': '翡翠叛乱', es: 'Rebelión de Jade' },
    logline: { ko: '고대 인형 군단의 각성.', en: 'Awakening of an ancient jade army.' },
    posterScene: 'jade warriors awakening action' },
  { id: 'snow-telegram', status: 'coming_soon', genre: 'romance', age: '12', hue: 200,
    titles: { ko: '눈송이 전보', en: 'Snow Telegram', ja: '雪の電報', 'zh-Hans': '雪花电报', es: 'Telegrama de Nieve' },
    logline: { ko: '눈이 내릴 때마다 오는 고백.', en: 'A confession delivered whenever it snows.' },
    posterScene: 'snow town telegram romance' },
  { id: 'amber-catacomb', status: 'coming_soon', genre: 'fantasy', age: '19', hue: 30,
    titles: { ko: '호박 지하묘', en: 'Amber Catacomb', ja: '琥珀の地下廟', 'zh-Hans': '琥珀地下陵', es: 'Catacumba de Ámbar' },
    logline: { ko: '호박에 봉인된 왕들의 속삭임.', en: 'Kings whispering from inside amber tombs.' },
    posterScene: 'amber tomb fantasy underground' },
  { id: 'ripple-jury', status: 'coming_soon', genre: 'drama', age: '15', hue: 195,
    titles: { ko: '파문 배심원', en: 'Ripple Jury', ja: '波紋の陪審', 'zh-Hans': '涟漪陪审团', es: 'Jurado de Ondas' },
    logline: { ko: '호수가 내린 유죄 판결.', en: 'A guilty verdict delivered by the lake itself.' },
    posterScene: 'lake courtroom drama' },
  { id: 'voltage-bloom', status: 'coming_soon', genre: 'action', age: '12', hue: 65,
    titles: { ko: '볼트 개화', en: 'Voltage Bloom', ja: 'ボルトの開花', 'zh-Hans': '伏特花开', es: 'Flor de Voltaje' },
    logline: { ko: '전기로 피어나는 거리의 꽃.', en: 'Flowers blooming from urban electric surges.' },
    posterScene: 'electric flowers city action' },
  { id: 'lumen-archive', status: 'coming_soon', genre: 'sf', age: '12', hue: 54,
    titles: { ko: '루멘 기록관', en: 'Lumen Archive', ja: 'ルーメン記録館', 'zh-Hans': '流明档案馆', es: 'Archivo Lumen' },
    logline: { ko: '빛의 속도로 저장된 기억 도서관.', en: 'A library storing memories at light speed.' },
    posterScene: 'light archive sci-fi library' },
  { id: 'silk-storm', status: 'coming_soon', genre: 'thriller', age: '19', hue: 340,
    titles: { ko: '비단 폭풍', en: 'Silk Storm', ja: '絹の嵐', 'zh-Hans': '丝绸风暴', es: 'Tormenta de Seda' },
    logline: { ko: '실크가 거리를 삼킨 날의 추적.', en: 'Tracking the day silk devoured the streets.' },
    posterScene: 'silk storm city thriller' },
  { id: 'orbit-bakery', status: 'coming_soon', genre: 'romance', age: 'all', hue: 28,
    titles: { ko: '궤도 베이커리', en: 'Orbit Bakery', ja: '軌道ベーカリー', 'zh-Hans': '轨道面包房', es: 'Panadería Orbital' },
    logline: { ko: '우주 정거장에서 굽는 첫 웨딩 케이크.', en: 'The first wedding cake baked on a space station.' },
    posterScene: 'space station bakery romance' },
  { id: 'rune-hospital', status: 'coming_soon', genre: 'fantasy', age: '15', hue: 170,
    titles: { ko: '룬 병원', en: 'Rune Hospital', ja: 'ルーン病院', 'zh-Hans': '符文医院', es: 'Hospital de Runas' },
    logline: { ko: '마법 부호로 수술하는 밤의 응급실.', en: 'An ER that operates with magical runes.' },
    posterScene: 'rune hospital fantasy night' },
  { id: 'cinder-bloom', status: 'coming_soon', genre: 'romance', age: '12', hue: 350,
    titles: { ko: '잔불 꽃다발', en: 'Cinder Bloom Bouquet', ja: '残火の花束', 'zh-Hans': '余烬花束', es: 'Ramo de Brasas' },
    logline: { ko: '타버린 꽃집에서 다시 피는 약속.', en: 'A promise reblooming from a burnt flower shop.' },
    posterScene: 'burnt flower shop romance rebloom' },
];